[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/traide"]

[project]
name = "traide-core-python"
version = "0.1.0"
description = "Traide core Python library"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [

    "gcloud-aio-storage>=9.6.1",
    "google-auth==2.48.0", # pin version to match other google cloud libraries
    "google-cloud-logging~=3.13",
    "greenlet~=3.3.0", # required to support async sqlalchemy
    "httpx~=0.28.1",
    "opentelemetry-api==1.39.1", # use specific version to match gcp-trace
    "opentelemetry-exporter-otlp-proto-http==1.39.1", # use specific version to match gcp-trace; only used locally for jaegar
    "opentelemetry-sdk==1.39.1", # use specific version to match gcp-trace
    "opentelemetry-exporter-prometheus==0.60b1", # use specific version to match gcp-trace
    "opentelemetry-instrumentation-sqlalchemy==0.60b1", # use specific version to match gcp-trace
    "opentelemetry-exporter-gcp-trace==1.11.0",
    "pgvector~=0.4.1",
    "psycopg[binary]~=3.3.3",
    "pydantic-settings~=2.13.1",
    "redis~=7.2.0",
    "sentry-sdk~=2.53.0",
    "sqlalchemy~=2.0.46",
    "structlog~=25.5",
    "tenacity~=9.1.4",
    "uvicorn~=0.41.0",
]

[project.optional-dependencies]
dev = [
    "ruff",
    "pyright",
    "pytest",
    "pre-commit",
]
fastapi = [
    "fastapi~=0.132.0",
    "opentelemetry-instrumentation-fastapi==0.60b1", # use specific version to match gcp-trace
    "prometheus-fastapi-instrumentator>=7.1.0",
]
faststream = [
    "faststream[cli,otel,prometheus,redis]~=0.6.6",
]

[dependency-groups]
dev = [
    "pre-commit>=4.3.0",
]

[tool.pyright]
typeCheckingMode = "strict"
reportMissingImports = true
reportUnusedImport = true
venvPath = "."
venv = ".venv"

[tool.ruff]
# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

# Same as Black.
line-length = 200
indent-width = 4

# Assume Python 3.12
target-version = "py312"

[tool.ruff.lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
select = ["E4", "E7", "E9", "F", "UP", "I"]
extend-select = ["C4", "SIM"] # "TCH"
ignore = ["E731"]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

# Enable auto-formatting of code examples in docstrings. Markdown,
# reStructuredText code/literal blocks and doctests are all supported.
#
# This is currently disabled by default, but it is planned for this
# to be opt-out in the future.
docstring-code-format = false

# Set the line length limit used when formatting code snippets in
# docstrings.
#
# This only has an effect when the `docstring-code-format` setting is
# enabled.
docstring-code-line-length = "dynamic"
